### ISSUE TITLE
Secret Agent Webhook Failures

### ISSUE THREAD

**Issue by jrcast** [ForgeRock/secret-agent#142]
We are getting reports of this error occurring out in the wild.  Initially believed that  happens when someone tries to install the operator in a cluster where it already exists. 

```
- Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "msecretagentconfiguration.kb.io": Post https://secret-agent-webhook-service.secret-agent-system.svc:443/mutate-secret-agent-secrets-forgerock-io-v1alpha1-secretagentconfiguration?timeout=30s: EOF
```

**Comment by Xroute53** [comment]
The error is while running either the base or full CDK via the script. I have tried this on GKE and minikube same error. Is someone looking into this.
There is no documentation on this troubleshooting for the same.
