### ISSUE TITLE
Need to update apiVersion of MutatingWebookConfiguration and ValidatingWebookConfiguration

### ISSUE THREAD

**Issue by jrcast** [ForgeRock/secret-agent#190]
```Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration```

```Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration```

**Comment by maxres-fr** [comment]
#192 solved this.
