### ISSUE TITLE
Unable to take backup of secrets to google secret manager

### ISSUE THREAD

**Issue by paritoshdubey** [ForgeRock/secret-agent#213]
We have deployed forgerock secret agent v1.1.3 in gke cluster(1.20 version) and we want to use workload identity for secret agent' secrets backup to google secret manager. after doing all the configuration, we are not able to backup secret to GSM and no secret are created in GSM. Please let us know how can we resolve the issue. Also I dont see any logs for for pod taking backup of secret to google secret manager(GSM)

**Comment by wstrange** [comment]
Just to confirm, you are *NOT* setting spec.appConfig.credentialsSecretName, correct? Workload identity wont be used if this is set.

I'd be inclined to try using a service account json file first, before proceeding to workload identity. This will let you validate that everything else is working before debugging workload identity.

**Comment by paritoshdubey** [comment]
We tried using workload identity. Now it is giving permission error. Problem is we cant apply secret managaer admin role due to company policy. Is there any other available IAM role in gcp that we can use it to work

**Comment by wstrange** [comment]
The service account needs sufficient IAM privileges to read/write/list secrets in GCP. There isn't any alternative if you want it to backup secrets to GCP.

**Comment by paritoshdubey** [comment]
It also gives error attempting to create secret in [global] constraint/resourcelocation org policy. is it possible to run in single region

**Comment by wstrange** [comment]
That error `"secret_ref":"platform-ca/ca.pem",` looks like SA is trying to reference that secret, and it does not exist yet.
Can you ensure secrets are ordered in SA in the order they need to get created in 
I'm not sure that is a GCP issue at this point.

I'd suggest paring down the secret agent file to just a single password secret, and then try to see if it gets created in GCP. This should make it easier to see if its a GCP secret problem or a problem with generating the secret itself

**Comment by jrcast** [comment]
If you have cloud backup enabled, the secret-agent looks for secrets in GSM first. If there's no secrets there, then it generates one and pushes that new secret to GSM. Depending on the order of secrets references  you might see a couple reconcile retries. If this is getting printed as errors, it should be a notice. Having said that, if you see the [sample config](https://github.com/ForgeRock/secret-agent/blob/master/config/samples/secret-agent_v1alpha1_secretagentconfiguration.yaml#L58) some secrets are dependent on a secret named `platform-config` which a CA named `ca` in it.  Do you have this secret present in your secretAgentConfiguration? 

If so, you can put it a the top of the file. Regardless we should just be printing this as notices and not errors.

**Comment by paritoshdubey** [comment]
@wstrange this error is not only for platform-ca. This error is coming for all also we are able to create secrets as k8s objects. We are getting this error because of organization policy restricting it for creating secrets globally. We have org policy that allow us to create resources only in 4 regions. How to enable this feature for selected regions

**Comment by wstrange** [comment]
> We have org policy that allow us to create resources only in 4 regions. How to enable this feature for selected regions

Secret agent is using the  official Google Go library for access to the api: https://github.com/googleapis/google-cloud-go 

I'm not sure there is anything we can do in the code itself. This appears to be an issue with configuring GCP roles and privileges to accomplish what you are attempting.  

What I would suggest is creating a small sample Job that uses the GCP CLI tool: https://cloud.google.com/sdk/gcloud/reference/secrets . The script can create a secret and read it back. 

Use that test Job (with workload identity or a json credential file) to debug the permissions/roles required for proper operation. Once that is working, you can try the same set of roles with secret agent.

**Comment by wstrange** [comment]
@paritoshdubey If it helps, here is a sample K8S Job that you can adapt to test your roles: https://github.com/ForgeRock/ds-operator/tree/master/tests/gcs

That example uses `gsutil`, but you can also try that with `gcloud` to test secret creation
