### ISSUE TITLE
GCP KMS Integration/guide

### ISSUE THREAD

**Issue by phr34ker** [ForgeRock/secret-agent#214]
Hi,

Are there any plans to integrate Google KMS or how would you integrate KMS (e.g. keys for token signing)?

**Comment by wstrange** [comment]
Hi -there are no plans for KMS integration.   
The roadmap is for more direct ForgeRock product integration with KMS systems, and/or using something like cert-manager.io for cert generation.  secret-agent is a short term solution for generating java keystores.
