### ISSUE TITLE
Is this open for commertial use?

### ISSUE THREAD

**Issue by Slowdive-Aideron** [ForgeRock/secret-agent#228]
Hi guys, 

awesome tool - i'm having fun with it. 
My question is if i can use this commercially. I know that this repo is under Apache2 , but are the docker images forgerock/secret-agent:v1.1.6 and gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0 also covered ? 

thank you

**Comment by lee-baines** [comment]
Hi, glad you like the product.  You can use this commercially.  The Apache2 license covers the docker image used for the controller.  The rbac-proxy belongs to kubebuilder so will be covered under their license.  Just to confirm though, we have stopped developing this product now and it's not a supported product by ForgeRock.  It's a tool we provide to assist users with their forgeops deployments for evaluation purposes.

**Comment by Slowdive-Aideron** [comment]
Hi, thanks for your answer. 


>  Just to confirm though, we have stopped developing this product now and it's not a supported product by ForgeRock. It's a tool we provide to assist users with their forgeops deployments for evaluation purposes.

It is the only Operator out there I can find that can create Azure KV secrets / keys.  akv2k8s, Official Azure Operators .. they all focus on syncing AKV -> K8s , not the other way around.

**Comment by lee-baines** [comment]
Thanks for the comments.  The reason for this statement is based on internal alignment with other products.  It may be something that we start to develop again in the future but for now we are unsure.
