### ISSUE TITLE
secret-agent should allow secrets to be retained after the CRD is deleted

### ISSUE THREAD

**Issue by wstrange** [ForgeRock/secret-agent#44]
As a deployer, I might want my secrets to be retained after the secret-agent CRD is deleted.  Just like data PVCs, secrets can be critical to the recovery of data. 

Suggest a top level boolean option such as `spec.retainSecrets` or some such thing (default: true)

**Comment by jrcast** [comment]
Seems the k8s way to deal with this is to set the `propagationPolicy` to `Orphan` when sending a DELETE request to the k8s api. Unfortunately kubectl does not support changing this field when using `kubectl delete` and it currently defaults to `Background` instead. 

When we create secrets we attach the CRD object in the `ownerReference` of each secret. This "ownerReference" is currently used to [filter the events that trigger a reconcile run](https://github.com/ForgeRock/secret-agent/blob/e725e097d7b223ddc331744498a34ed9cd50d901/controllers/secretagentconfiguration_controller.go#L177). Typically we would want to trigger the reconciler if:
a. we modify the CR object and/or 
b. if the secret is modified.

We have a few options:

1. Create objects without ownership. This requires figuring out a different filter criteria for the reconciler.
2. Continue owning the secrets and use a pre-delete webhook hook to disown the secrets when the delete request is received.

more info on GC: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy

**Comment by jrcast** [comment]
I think I will pursue option 2 for now.  I am not exactly a fan of the first one.

**Comment by wstrange** [comment]
OK - if this is getting too complicated we can defer for now. Getting the jceks keystore working is more important

**Comment by jrcast** [comment]
if the user wants to persist the secrets, they must use cloud backup or back up the secrets manually.
